name: Generate PR from Changes

on:
  repository_dispatch:
    types: [trigger-pr]

jobs:
  generate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create New Branch
        run: |
          git checkout -b new-token-design

      - name: Set up .env with Token
        run: echo "GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}" > .env

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Nx and dependencies
        run: |
          pnpm install --no-frozen-lockfile

      - name: Create PR
        run: |
          npx nx run tampan-lib:token

      - name: Commit and Push Changes
        run: |
          git config user.email "agungvr@gmail.com"
          git config user.name "Agung Nugraha"
          git add .
          git commit -m "fix: new token updates"
          git pull origin main
          git push origin new-token-design

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          commit-message: 'fix: auto generated PR'
          title: 'fix: auto generated PR'
          body: 'This PR was automatically generated.'
          base: main
          branch: new-token-design
